### ISSUE TITLE
Ajustar o diagrama de Casos de Uso

### ISSUE THREAD

**Issue by Gilbert-Silva** [PI-InfoWeb-CNAT/agendamento_barbearia#17]
Ligar todos os atores ao caso de uso quando o CDU puder ser realizado por mais de um ator
Incluir o CDU - Manter a Agenda Pessoal para o funcionário poder ajustar a própria agenda

**Comment by luisgustavopn** [comment]
Já está atualizado na pasta [agendamento_barbearia](https://github.com/PI-InfoWeb-CNAT/agendamento_barbearia)/[docs](https://github.com/PI-InfoWeb-CNAT/agendamento_barbearia/tree/main/docs)/[diagramas](https://github.com/PI-InfoWeb-CNAT/agendamento_barbearia/tree/main/docs/diagramas)/Novo diagrama de CDU.drawio.pdf
